on: [push, pull_request]
name: Build and lint
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint code
        run: |
          go get -u golang.org/x/lint/golint
          golint .
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build .
